- artifact-builder/test.sh
- lexevs-cts2-builder/test.sh
- lexevs-remote-testrunner/test.sh
Updated scripts to include MAVEN_OPTS and ANT_OPTS settings.
> LEXEVS-2314 Updated scripts to include MAVEN_OPTS and ANT_OPTS settings.

- artifact-builder/test.sh
- lexevs-cts2-builder/test.sh
- lexevs-remote-testrunner/test.sh
LEXEVS-2402 Updated build scripts to include additional ANT_OPS and MAVEN_OPTS.
> LEXEVS-2402 Updated build scripts to include additional ANT_OPS and MAVEN_OPTS

- artifact-builder/Dockerfile
- lexevs-cts2-builder/Dockerfile
- lexevs-cts2/Dockerfile
- lexevs-load/Dockerfile
- lexevs-remote-testrunner/Dockerfile
- lexevs-remote/Dockerfile
- lexevs-testrunner/Dockerfile
- uriresolver/Dockerfile
LEXEVS-2608 Updated Docker files to pull Java 8
> LEXEVS-2608 Updated Docker files to pull Java 8

- artifact-builder/Dockerfile
- artifact-builder/test.sh
- lexevs-remote-testrunner/Dockerfile
- lexevs-testrunner/Dockerfile
- test.sh
Lexevs-2430 Updated for Java 1.8
> Lexevs-2430 Updated for Java 1.8

- mysql/init/init.sh
Bugfix/lexevs 2646 Updating MySQL command to work with updated MySQL 5.5
> Bugfix/lexevs 2646 Updating MySQL command to work with updated MySQL 5.5 

- lexevs-load/run.sh
LEXEVS-2579.  Updating load script for remote api tests to prevent overlapping source loads and other errors
> LEXEVS-2579.  Updating load script for remote api tests to prevent overlapping source loads and other errors

- lexevs-load/run.sh
LEXEVS-2579 Updating load script for remote api tests to prevent overlapping source loads and other errors
> LEXEVS-2579 Updating load script for remote api tests to prevent overlapping source loads and other errors

- lexevs-cts2/Dockerfile
- lexevs-remote/Dockerfile
- uriresolver/Dockerfile
Bugfix/lexsystest 1 - Updating tomcat to 8.5.11-jre8
> Bugfix/lexsystest 1 - Updating tomcat to 8.5.11-jre8

- mysql/Dockerfile
- mysql/init/init.sh
LEXSYSTEST-7 Updated MySQL version to 5.6 and the command to create the DB
> LEXSYSTEST-7 Updated MySQL version to 5.6 and the command to create the DB

- artifact-builder/test.sh
- lexevs-remote-testrunner/Test.properties
- lexevs-remote/run.sh
LEXSYSTEST-11 Updated references of lexevsapi64 to lexevsapi65.
> LEXSYSTEST-11 Updated references of lexevsapi64 to lexevsapi65.

- lexevs-cts2-testrunner/Dockerfile
- lexevs-cts2-testrunner/cts2Calls_spec.js
- lexevs-cts2-testrunner/test.sh
- test.sh
Bugfix/lexevscts2-62 Adding REST service tests - Frisby
> Bugfix/lexevscts2-62 Adding REST service tests

- artifact-builder/Dockerfile
- artifact-builder/test.sh
- lexevs-cts2-builder/Dockerfile
- lexevs-cts2-builder/test.sh
- lexevs-cts2-testrunner/Dockerfile
- lexevs-cts2-testrunner/cts2Calls_spec.js
- lexevs-cts2-testrunner/test.sh
- lexevs-cts2/Dockerfile
- lexevs-load/Dockerfile
- lexevs-load/run.sh
- lexevs-remote-testrunner/Dockerfile
- lexevs-remote-testrunner/Test.properties
- lexevs-remote-testrunner/test.sh
- lexevs-remote/Dockerfile
- lexevs-remote/run.sh
- lexevs-testrunner/Dockerfile
- mysql/Dockerfile
- mysql/init/init.sh
- test.sh
- uriresolver/Dockerfile
Bugfix/lexsystest 15 Merging 6.5.0 branch to master.
This updates the master branch with the latest changes on the 6.5.0 branch.
> Bugfix/lexsystest 15 Merging 6.5.0 branch to master

- lexevs-cts2/Dockerfile
- lexevs-remote/Dockerfile
- mysql/Dockerfile
- test.sh
- uriresolver/Dockerfile
Bugfix/lexsystest 19 - pulling tomcat and mysql images from NCI Nexus Docker server. 
This requires an id/pw for the NCI Nexus Docker server to be passed in.
> Bugfix/lexsystest 19 - pulling tomcat and mysql images from NCI Nexus Docker server

- lexevs-load/run.sh
…version containing cumulative OWL2 loader use case updates.
> LEXSYSTEST-36.  Updating OWL2 test source to a more recent version

- lexevs-cts2-testrunner/Dockerfile
- lexevs-cts2-testrunner/cts2Calls_spec.js
- lexevs-cts2-testrunner/test.sh
Bugfix/lexsystest 38 Updating CTS2 REST tests for updated testing harness (frisby/nodejs)
> Bugfix/lexsystest 38 Updating CTS2 REST tests

- lexevs-cts2-testrunner/Dockerfile
- lexevs-cts2-testrunner/cts2Calls_spec.js
- lexevs-cts2-testrunner/test.sh
Updating CTS2 REST tests for updated testing harness (frisby/nodejs)
Merging changes to the DEV branch.
> Bugfix/lexsystest 38 Updating CTS2 REST tests (for DEV)

- artifact-builder/Dockerfile
- artifact-builder/test.sh
- lexevs-cts2-builder/test.sh
- lexevs-cts2-testrunner/cts2Calls_spec.js
- lexevs-cts2-testrunner/test.sh
- lexevs-cts2/Dockerfile
- lexevs-remote/Dockerfile
- lexevs-testrunner/test.sh
- mysql/Dockerfile
- test.sh
- uriresolver/Dockerfile
Bugfix/lexsystest 54 Fixing mySQL permission error and copying lexevs artifacts locally.
> Bugfix/lexsystest 54 Fixing mySQL permission error and copying lexevs artifacts locally.

- lexevs-cts2-testrunner/cts2Calls_spec.js
LEXSYSTEST-59 Updated tests to run correctly searching in JSON arrays
> LEXSYSTEST-59 Updated tests to run correctly searching in JSON arrays

- lexevs-cts2-testrunner/Dockerfile
LEXSYSTEST-60 Install specific version of frisby and jasmine.
> LEXSYSTEST-60 Install specific version of frisby and jasmine.

- lexevs-cts2-testrunner/Dockerfile
LEXSYSTEST-73 - merge frisby and jasmine install version update to 6.5.0 branch.
> LEXSYSTEST-73 - merge frisby and jasmine install version update to 6.5.0 branch.

- lexevs-cts2-testrunner/cts2Calls_spec.js
LEXSYSTEST-80 Updated test to reflect new number of value sets
> LEXSYSTEST-80 Updated test to reflect new number of value sets

- lexevs-cts2-builder/test.sh
- test.sh
LEXSYSTEST-84 - If builds fail, then exit system tests.
> LEXSYSTEST-84 - If builds fail, then exit system tests.

- lexevs-cts2-testrunner/cts2Calls_spec.js
LEXSYSTEST-89 Updated version of CTS2 Framework to 1.3.3.1.FINAL in REST tests
> LEXSYSTEST-89 Updated version of CTS2 Framework to 1.3.3.1.FINAL in REST tests

- lexevs-load/run.sh
LEXSYSTEST-93 Updated lexevs load script to run BuildResolvedAndAssertedValueSetIndexes.sh
> LEXSYSTEST-93 Updated lexevs load script to run BuildResolvedAndAssertedValueSetIndexes.sh

- test.sh
LEXSYSTEST-97 Update main test to distinguish when skip was called or if the build actually failed.
> LEXSYSTEST-97 Update main test to distinguish when skip was called or if the build actually failed.

- lexevs-remote-testrunner/test.sh
LEXSYSTEST-101 - Updated remote api test to point to a target "alltests".
> LEXSYSTEST-101 - Updated remote api test to point to a target "alltests".

- mysql/Dockerfile
- mysql/my.cnf
LEXSYSTEST-125 setting barracuda file format on mysql docker image.
> LEXSYSTEST-125 setting barracuda file format on mysql docker image.

- lexevs-cts2-testrunner/cts2Calls_spec.js
LEXSYSTEST-131 added tests for resolving a value set.
> LEXSYSTEST-131 added tests for resolving a value set.

- lexevs-cts2-testrunner/cts2Calls_spec.js
LEXSYSTEST-135 Added test for resolved value set with multiple parents.
> LEXSYSTEST-135 Added test for resolved value set with multiple parents.

- lexevs-cts2-testrunner/cts2Calls_spec.js
LEXSYSTEST-151 - Updated value set counts based on test source updates (LEXEVS-4552, LEXEVSREM-378)
> LEXSYSTEST-151 - Updated value set counts based on test source updates (LEXEVS-4552, LEXEVSREM-378)

- lexevs-graph-resolve-testrunner/graph-resolveCalls_spec.js
- test.sh
LEXSYSTEST-167 - Added tests calls for graph-resolve API
> LEXSYSTEST-167 - Added tests calls for graph-resolve API

- lexevs-cts2-testrunner/cts2Calls_spec.js
LEXSYSTEST-172 updating cts2 version number.
> LEXSYSTEST-172 updating cts2 version number.
